spring.application.name=WaterDelivery
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/Encrypt
spring.datasource.username=postgres
spring.datasource.password=2911

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.show_sql=true

spring.mvc.hiddenmethod.filter.enable=true
spring.jpa.hibernate.ddl-auto=update

management.endpoints.web.exposure.include=mappings
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=file:src/main/resources/templates/
spring.thymeleaf.suffix=.html

spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true